import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";

import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { UserProvider } from "@/Components/Context";
import Provider from "../Components/Provider";
import BasicModal from "@/Components/Modal";
import Authentication from "@/Components/Authentication";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Learn Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <Provider> */}

        <UserProvider>
          <ToastContainer />

          <BasicModal />

          {children}
        </UserProvider>

        {/* </Provider> */}
      </body>
    </html>
  );
}
